from __future__ import annotations

import uuid

import sqlalchemy as sa
from sqlalchemy import Enum, ForeignKey, Integer, JSON, String, Text, UniqueConstraint, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.base import Base, CreatedAtMixin, TimestampMixin
from backend.app.db.vector_type import TsvectorType, VectorType
from backend.app.models.enums import BankDocumentSourceKind


class Bank(TimestampMixin, Base):
    __tablename__ = "banks"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    owner_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    owner = relationship("User", back_populates="banks")
    documents = relationship(
        "BankDocument",
        back_populates="bank",
        cascade="all, delete-orphan",
        order_by="BankDocument.updated_at.desc()",
    )
    facts = relationship(
        "BankFact",
        back_populates="bank",
        cascade="all, delete-orphan",
        order_by="BankFact.created_at.desc()",
    )
    entities = relationship(
        "BankEntity",
        back_populates="bank",
        cascade="all, delete-orphan",
        order_by="BankEntity.name.asc()",
    )


class BankDocument(TimestampMixin, Base):
    __tablename__ = "bank_documents"
    __table_args__ = (
        UniqueConstraint(
            "bank_id",
            "source_kind",
            "source_key",
            name="uq_bank_documents_bank_source_identity",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    bank_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("banks.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    source_kind: Mapped[BankDocumentSourceKind] = mapped_column(
        Enum(
            BankDocumentSourceKind,
            native_enum=False,
            length=32,
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=False,
        default=BankDocumentSourceKind.UPLOAD,
    )
    source_key: Mapped[str] = mapped_column(Text, nullable=False)
    external_id: Mapped[str | None] = mapped_column(Text)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    bytes: Mapped[int] = mapped_column(Integer, nullable=False)
    document_metadata: Mapped[dict[str, object]] = mapped_column(
        "metadata",
        JSON,
        nullable=False,
        default=dict,
    )

    bank = relationship("Bank", back_populates="documents")
    chunks = relationship(
        "BankDocumentChunk",
        back_populates="document",
        cascade="all, delete-orphan",
        order_by="BankDocumentChunk.chunk_index",
    )
    facts = relationship(
        "BankFact",
        back_populates="document",
        cascade="all, delete-orphan",
        order_by="BankFact.created_at.desc()",
    )
    entities = relationship(
        "BankEntity",
        back_populates="document",
        cascade="all, delete-orphan",
        order_by="BankEntity.name.asc()",
    )


class BankDocumentChunk(Base):
    __tablename__ = "bank_document_chunks"
    __table_args__ = (
        UniqueConstraint(
            "document_id",
            "chunk_index",
            name="uq_bank_document_chunks_document_chunk",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("bank_documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    heading_path: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False, default="", server_default="")
    embedding: Mapped[list[float] | None] = mapped_column(VectorType(1536), nullable=True)
    model: Mapped[str] = mapped_column(
        String, nullable=False, default="", server_default=""
    )
    # Generated by Postgres (GENERATED ALWAYS AS STORED); never written by the app.
    content_tsv: Mapped[str | None] = mapped_column(
        "content_tsv",
        TsvectorType,
        nullable=True,
        server_default=sa.FetchedValue(),
        info={"derived": True},
    )

    document = relationship("BankDocument", back_populates="chunks")
    facts = relationship(
        "BankFact",
        back_populates="chunk",
        cascade="all, delete-orphan",
        order_by="BankFact.created_at.desc()",
    )


class BankEntity(CreatedAtMixin, Base):
    __tablename__ = "bank_entities"
    __table_args__ = (
        UniqueConstraint(
            "document_id",
            "canonical_name",
            "entity_type",
            name="uq_bank_entities_document_canonical_type",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    bank_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("banks.id", ondelete="CASCADE"),
        nullable=False,
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("bank_documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    canonical_name: Mapped[str] = mapped_column(Text, nullable=False)
    entity_type: Mapped[str] = mapped_column(String(32), nullable=False, default="other")

    bank = relationship("Bank", back_populates="entities")
    document = relationship("BankDocument", back_populates="entities")
    observations = relationship(
        "BankObservation",
        back_populates="entity",
        cascade="all, delete-orphan",
        order_by="BankObservation.created_at.asc()",
    )


class BankFact(CreatedAtMixin, Base):
    __tablename__ = "bank_facts"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    bank_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("banks.id", ondelete="CASCADE"),
        nullable=False,
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("bank_documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    chunk_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("bank_document_chunks.id", ondelete="CASCADE"),
    )
    statement: Mapped[str] = mapped_column(Text, nullable=False)
    source_excerpt: Mapped[str | None] = mapped_column(Text)
    heading_path: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    extraction_model: Mapped[str] = mapped_column(String, nullable=False, default="", server_default="")
    embedding: Mapped[list[float] | None] = mapped_column(VectorType(1536), nullable=True)
    model: Mapped[str] = mapped_column(String, nullable=False, default="", server_default="")
    content_tsv: Mapped[str | None] = mapped_column(
        "content_tsv",
        TsvectorType,
        nullable=True,
        server_default=sa.FetchedValue(),
        info={"derived": True},
    )

    bank = relationship("Bank", back_populates="facts")
    document = relationship("BankDocument", back_populates="facts")
    chunk = relationship("BankDocumentChunk", back_populates="facts")
    observations = relationship(
        "BankObservation",
        back_populates="fact",
        cascade="all, delete-orphan",
        order_by="BankObservation.created_at.asc()",
    )


class BankObservation(CreatedAtMixin, Base):
    __tablename__ = "bank_observations"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    fact_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("bank_facts.id", ondelete="CASCADE"),
        nullable=False,
    )
    entity_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("bank_entities.id", ondelete="SET NULL"),
    )
    role: Mapped[str | None] = mapped_column(String(32))
    content: Mapped[str] = mapped_column(Text, nullable=False)

    fact = relationship("BankFact", back_populates="observations")
    entity = relationship("BankEntity", back_populates="observations")
