from __future__ import annotations

import uuid
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import DateTime, Enum, ForeignKey, Index, Integer, JSON, String, Text, Uuid
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Mapped, mapped_column

from backend.app.core.ids import uuid7
from backend.app.db.base import Base, CreatedAtMixin
from backend.app.db.vector_type import TsvectorType
from backend.app.models.enums import CodeNodeType

uuid_list_type = JSON().with_variant(
    postgresql.ARRAY(postgresql.UUID(as_uuid=False)),
    "postgresql",
)


class CodeNode(CreatedAtMixin, Base):
    __tablename__ = "code_nodes"
    __table_args__ = (
        Index("idx_code_nodes_repo_file", "repository_id", "file_path"),
        Index("uq_code_nodes_repo_qualified_name", "repository_id", "qualified_name", unique=True),
        Index("idx_code_nodes_source_file", "repository_id", "source_file_id"),
        Index("idx_code_nodes_symbol_key", "repository_id", "symbol_key"),
        Index(
            "idx_code_nodes_role",
            "repository_id",
            "role",
            postgresql_where="role IS NOT NULL",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid7,
    )
    repository_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
    )
    source_file_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("source_files.id", ondelete="CASCADE"),
    )
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    qualified_name: Mapped[str] = mapped_column(Text, nullable=False)
    symbol_key: Mapped[str | None] = mapped_column(Text)
    node_type: Mapped[CodeNodeType] = mapped_column(
        Enum(
            CodeNodeType,
            native_enum=False,
            length=16,
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        nullable=False,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    language: Mapped[str] = mapped_column(String(64), nullable=False)
    start_line: Mapped[int] = mapped_column(nullable=False)
    end_line: Mapped[int] = mapped_column(nullable=False)
    start_byte: Mapped[int | None] = mapped_column(Integer)
    end_byte: Mapped[int | None] = mapped_column(Integer)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    signature: Mapped[str | None] = mapped_column(Text)
    doc_comment: Mapped[str | None] = mapped_column(Text)
    summary: Mapped[str | None] = mapped_column(Text)
    role: Mapped[str | None] = mapped_column(Text)
    # index=True needed for fresh-create environments (test fixtures, dev
    # setups using Base.metadata.create_all) — prod gets the partial index
    # `WHERE parent_id IS NOT NULL` from migration 0057. Without an index
    # the self-FK ON DELETE CASCADE does a seq scan per cascaded child,
    # which on a 130k-row table hits statement_timeout (incident
    # 2026-05-19: 297s on a single DELETE).
    parent_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("code_nodes.id", ondelete="CASCADE"),
        index=True,
    )
    callers: Mapped[list[str]] = mapped_column(
        uuid_list_type,
        nullable=False,
        default=list,
    )
    callees: Mapped[list[str]] = mapped_column(
        uuid_list_type,
        nullable=False,
        default=list,
    )
    node_metadata: Mapped[dict[str, object]] = mapped_column(
        "metadata",
        JSON,
        nullable=False,
        default=dict,
    )
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    first_seen_commit: Mapped[str | None] = mapped_column(Text)
    last_changed_commit: Mapped[str | None] = mapped_column(Text)
    last_changed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Generated by Postgres (GENERATED ALWAYS AS STORED); never written by the app.
    content_tsv: Mapped[str | None] = mapped_column(
        "content_tsv",
        TsvectorType,
        nullable=True,
        server_default=sa.FetchedValue(),
        info={"derived": True},
    )
