from __future__ import annotations

import uuid

import sqlalchemy as sa
from sqlalchemy import ForeignKey, Integer, JSON, String, Text, UniqueConstraint, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.base import Base, TimestampMixin
from backend.app.db.vector_type import TsvectorType, VectorType


class RepoDocument(TimestampMixin, Base):
    __tablename__ = "repo_documents"
    __table_args__ = (
        UniqueConstraint("repository_id", "file_path", name="uq_repo_documents_repo_file_path"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    repository_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
    )
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str | None] = mapped_column(Text)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    bytes: Mapped[int] = mapped_column(Integer, nullable=False)

    chunks = relationship(
        "RepoDocumentChunk",
        back_populates="document",
        cascade="all, delete-orphan",
        order_by="RepoDocumentChunk.chunk_index",
    )


class RepoDocumentChunk(Base):
    __tablename__ = "repo_document_chunks"
    __table_args__ = (
        UniqueConstraint("document_id", "chunk_index", name="uq_repo_document_chunks_document_chunk"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("repo_documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    heading_path: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False, default="", server_default="")
    mentions: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    embedding: Mapped[list[float] | None] = mapped_column(VectorType(1536), nullable=True)
    model: Mapped[str] = mapped_column(
        String, nullable=False, default="", server_default=""
    )
    # Generated by Postgres (GENERATED ALWAYS AS STORED); never written by the app.
    content_tsv: Mapped[str | None] = mapped_column(
        "content_tsv",
        TsvectorType,
        nullable=True,
        server_default=sa.FetchedValue(),
        info={"derived": True},
    )

    document = relationship("RepoDocument", back_populates="chunks")
