apiVersion: v1
kind: Service
metadata:
  name: {{ include "cograph.webServiceName" . }}
  labels:
    {{- include "cograph.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "cograph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http

