<script setup lang="ts">
// Mermaid renderer for the docs site.
//
// Why this exists instead of vitepress-plugin-mermaid's component: that one
// hardcodes `config.theme = "dark"` whenever <html> carries `.dark`, which
// throws away the palette we pass and falls back to mermaid's stock dark theme.
// VitePress config is static, so there is no way to hand the plugin a second,
// dark-mode `themeVariables` set. The plugin is kept for its Vite/markdown
// wiring (SSR externals and the mermaid dependency pre-bundle, which track
// mermaid's own transitive deps); rendering happens here, where `isDark` is
// reactive.
//
// Mirrors `web/src/components/shared/MermaidDiagram.tsx`: same theme variables,
// same `themeCSS`, same SVG sanitisation, same render cancellation, same
// wait-for-fonts. Keep the two in step.

import { useData } from "vitepress";
import { onMounted, onUnmounted, ref, watch } from "vue";

// Generated by docs/scripts/sync-tokens.mjs from the app's design tokens.
// Mermaid needs literal colours (khroma derives shades from them), and this
// keeps them from drifting when the app palette moves.
import palette from "./mermaid-palette.json";

const props = defineProps<{ id: string; graph: string }>();

const svg = ref("");
const error = ref("");
const { isDark } = useData();

const source = decodeURIComponent(props.graph).trim();

// Ported verbatim from the app. The foreignObject rules are not cosmetic:
// mermaid's HTML-label sizing pass underestimates text width when the
// configured font differs from the one it measures with, which clips or skews
// long labels. Letting the foreignObject overflow and re-pinning the inner div
// to its centre makes labels grow symmetrically instead.
const THEME_CSS = `
  .nodeLabel, .nodeLabel p, .edgeLabel, .edgeLabel p, .cluster-label, .cluster-label p {
    word-break: normal;
    overflow-wrap: normal;
  }
  foreignObject {
    overflow: visible;
  }
  foreignObject > div {
    position: relative !important;
    left: 50% !important;
    top: 50% !important;
    transform: translate(-50%, -50%) !important;
    width: auto !important;
    max-width: none !important;
    display: inline-block !important;
  }
  .nodeLabel,
  .nodeLabel p {
    overflow: visible;
  }
`;

/**
 * Strip anything executable out of mermaid's SVG before it reaches v-html.
 *
 * `securityLevel: "antiscript"` removes `<script>` from the diagram *source*,
 * but it does not strip event-handler attributes or `javascript:` URLs from the
 * rendered output — the app documents exactly this and sanitises for the same
 * reason. This site is public, so an unsanitised diagram is a stored-XSS path
 * through any documentation change.
 *
 * DOM-based rather than a regex: parsing and re-serialising cannot be fooled by
 * creative attribute quoting.
 */
function sanitizeSvg(raw: string): string {
  if (typeof DOMParser === "undefined") return raw;

  // Mermaid emits HTML void tags (<br>) that a strict XML parser rejects.
  const normalised = raw.replace(/<(br|hr|img|input)([^>]*?)(?<!\/)>/g, "<$1$2/>");
  const doc = new DOMParser().parseFromString(normalised, "image/svg+xml");
  const root = doc.documentElement;

  // Browsers disagree on where a parse failure lands: Firefox makes
  // <parsererror> the root, Chrome and WebKit nest it inside an svg-named root.
  const parseError =
    root?.nodeName === "parsererror"
      ? root
      : (root?.getElementsByTagName("parsererror")[0] ?? null);
  if (!root || parseError) {
    throw new Error(parseError?.textContent?.trim() || "Diagram SVG failed to parse");
  }

  const queue: Element[] = [root];
  while (queue.length) {
    const el = queue.shift();
    if (!el) continue;

    if (el.tagName.toLowerCase() === "script") {
      el.remove();
      continue;
    }
    for (const attr of Array.from(el.attributes)) {
      const name = attr.name.toLowerCase();
      if (name.startsWith("on")) {
        el.removeAttribute(attr.name);
        continue;
      }
      if (name === "href" || name === "xlink:href") {
        const value = attr.value.trim().toLowerCase();
        if (value.startsWith("javascript:") || value.startsWith("data:text/html")) {
          el.removeAttribute(attr.name);
        }
      }
    }
    for (const child of Array.from(el.children)) queue.push(child);
  }

  return new XMLSerializer().serializeToString(root);
}

let seq = 0;
// Monotonic token: mermaid.initialize mutates a global singleton, so a theme
// flip mid-render could otherwise let a stale light-mode SVG overwrite the
// dark-mode one that superseded it.
let generation = 0;
let disposed = false;

async function render() {
  const mine = ++generation;

  // Mermaid measures label widths with the configured font. If Inter has not
  // loaded yet it measures a fallback and every box comes out the wrong size.
  if (typeof document !== "undefined" && document.fonts) {
    try {
      await Promise.all([
        document.fonts.load('400 13px "Inter Variable"'),
        document.fonts.load('500 13px "Inter Variable"'),
        document.fonts.load('600 13px "Inter Variable"'),
      ]);
      await document.fonts.ready;
    } catch {
      // Best-effort — a font that fails to load must not block the diagram.
    }
  }
  if (disposed || mine !== generation) return;

  // Dynamic import keeps mermaid (~700 kB) out of the server bundle and off the
  // critical path for pages with no diagram.
  const mermaid = (await import("mermaid")).default;
  if (disposed || mine !== generation) return;

  mermaid.initialize({
    startOnLoad: false,
    theme: "base",
    // Still strips <script> from the diagram source, while keeping the HTML
    // label path that dagre-wrapper requires in mermaid 11. Not sufficient on
    // its own — see sanitizeSvg.
    securityLevel: "antiscript",
    fontFamily: 'var(--font-sans), "Inter Variable", "Inter", sans-serif',
    flowchart: {
      htmlLabels: true,
      // The one deliberate divergence from the app, which uses `true`.
      // In-product diagrams sit in a wide panel; here they sit in a ~690px
      // prose column, and scaling a wide flowchart down to fit makes the labels
      // unreadable. Natural size plus container scroll is the better trade.
      useMaxWidth: false,
      padding: 16,
      nodeSpacing: 60,
      rankSpacing: 70,
      curve: "basis",
    },
    sequence: { useMaxWidth: false, wrap: true, messageFontSize: 13 },
    themeVariables: isDark.value ? palette.dark : palette.light,
    themeCSS: THEME_CSS,
  });

  try {
    const { svg: out } = await mermaid.render(`${props.id}-${++seq}`, source);
    if (disposed || mine !== generation) return;
    svg.value = sanitizeSvg(out);
    error.value = "";
  } catch (err) {
    if (disposed || mine !== generation) return;
    error.value = err instanceof Error ? err.message : "Diagram render failed";
    svg.value = "";
  }
}

onMounted(render);
onUnmounted(() => {
  disposed = true;
});
// Re-render on theme flip: mermaid bakes colours into the SVG, so a palette
// change cannot be picked up by CSS alone.
watch(isDark, render);
</script>

<template>
  <div v-if="error" class="cograph-mermaid-error" role="alert">
    <p><strong>Couldn't render diagram</strong></p>
    <p>{{ error }}</p>
    <pre>{{ source }}</pre>
  </div>
  <!-- eslint-disable-next-line vue/no-v-html -- sanitised above: scripts, event
       handlers and javascript:/data:text/html URLs are stripped from the SVG. -->
  <div v-else class="cograph-mermaid" v-html="svg" />
</template>

<style scoped>
.cograph-mermaid {
  display: flex;
  /* `safe center` keeps a narrow diagram centred while preventing a diagram
     wider than the column from having its left edge scrolled out of reach —
     plain `center` on a flex container clips the overflow start. */
  justify-content: safe center;
  overflow-x: auto;
  margin: 1.5rem 0;
  padding: 1rem;
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-md);
  background: var(--color-bg-surface);
  /* Reserve height so the page does not jump when the diagram resolves. */
  min-height: 4rem;
}

.cograph-mermaid :deep(svg) {
  /* `useMaxWidth: false` means mermaid emits explicit dimensions; leave them
     alone so labels keep their intended size and let the container scroll. */
  flex: none;
  height: auto;
}

.cograph-mermaid-error {
  margin: 1.5rem 0;
  padding: 0.875rem 1rem;
  border: 1px solid var(--color-danger);
  border-radius: var(--radius-md);
  background: var(--color-bg-surface);
  font-size: 0.875rem;
}

.cograph-mermaid-error pre {
  margin: 0.5rem 0 0;
  overflow-x: auto;
  color: var(--color-fg-muted);
  font-family: var(--font-mono);
  font-size: 0.8125rem;
}
</style>
